export const APPLICATION_SETTING_REQUEST = 'APPLICATION_SETTING_REQUEST';
export const APPLICATION_SETTING_SUCCESS = 'APPLICATION_SETTING_SUCCESS';
export const APPLICATION_SETTING_FAIL = 'APPLICATION_SETTING_SAVE';
export const APPLICATION_SETTING_RESET = 'APPLICATION_SETTING_RESET';

export const APPLICATION_SETTING_LIST_REQUEST = 'APPLICATION_SETTING_LIST_REQUEST';
export const APPLICATION_SETTING_LIST_SUCCESS = 'APPLICATION_SETTING_LIST_SUCCESS';
export const APPLICATION_SETTING_LIST_FAIL = 'APPLICATION_SETTING_LIST_FAIL';