export const APPLICATION_SETTING_REQUEST = 'APPLICATION_SETTING_SAVE';
export const APPLICATION_SETTING_SUCCESS = 'APPLICATION_SETTING_SAVE';
export const APPLICATION_SETTING_FAIL = 'APPLICATION_SETTING_SAVE';
export const APPLICATION_SETTING_RESET = 'APPLICATION_SETTING_RESET';