export const ATTRIBUTE_CREATE_REQUEST = "ATTRIBUTE_CREATE_REQUEST";
export const ATTRIBUTE_CREATE_SUCCESS = "ATTRIBUTE_CREATE_SUCCESS";
export const ATTRIBUTE_CREATE_FAIL = "ATTRIBUTE_CREATE_FAIL";
export const ATTRIBUTE_CREATE_RESET = "ATTRIBUTE_CREATE_RESET";

export const ATTRIBUTE_LIST_REQUEST = "ATTRIBUTE_LIST_REQUEST";
export const ATTRIBUTE_LIST_SUCCESS = "ATTRIBUTE_LIST_SUCCESS";
export const ATTRIBUTE_LIST_FAIL = "ATTRIBUTE_LIST_FAIL";

export const ATTRIBUTE_VALUE_CREATE_REQUEST = "ATTRIBUTE_VALUE_CREATE_REQUEST";
export const ATTRIBUTE_VALUE_CREATE_SUCCESS = "ATTRIBUTE_VALUE_CREATE_SUCCESS";
export const ATTRIBUTE_VALUE_CREATE_FAIL = "ATTRIBUTE_VALUE_CREATE_FAIL";
export const ATTRIBUTE_VALUE_CREATE_RESET = "ATTRIBUTE_VALUE_CREATE_RESET";

export const ATTRIBUTE_VALUE_LIST_REQUEST = "ATTRIBUTE_VALUE_LIST_REQUEST";
export const ATTRIBUTE_VALUE_LIST_SUCCESS = "ATTRIBUTE_VALUE_LIST_SUCCESS";
export const ATTRIBUTE_VALUE_LIST_FAIL = "ATTRIBUTE_VALUE_LIST_FAIL";


export const FEATURES_CREATE_REQUEST = "FEATURES_CREATE_REQUEST";
export const FEATURES_CREATE_SUCCESS = "FEATURES_CREATE_SUCCESS";
export const FEATURES_CREATE_FAIL = "FEATURES_CREATE_FAIL";
export const FEATURES_CREATE_RESET = "FEATURES_CREATE_RESET";

export const FEATURES_LIST_REQUEST = "FEATURES_LIST_REQUEST";
export const FEATURES_LIST_SUCCESS = "FEATURES_LIST_SUCCESS";
export const FEATURES_LIST_FAIL = "FEATURES_LIST_FAIL";



export const FEATURES_VALUE_CREATE_REQUEST = "FEATURES_VALUE_CREATE_REQUEST";
export const FEATURES_VALUE_CREATE_SUCCESS = "FEATURES_VALUE_CREATE_SUCCESS";
export const FEATURES_VALUE_CREATE_FAIL = "FEATURES_VALUE_CREATE_FAIL";
export const FEATURES_VALUE_CREATE_RESET = "FEATURES_VALUE_CREATE_RESET";

export const FEATURES_VALUE_LIST_REQUEST = "FEATURES_VALUE_LIST_REQUEST";
export const FEATURES_VALUE_LIST_SUCCESS = "FEATURES_VALUE_LIST_SUCCESS";
export const FEATURES_VALUE_LIST_FAIL = "FEATURES_VALUE_LIST_FAIL";




