export const BRAND_REQUEST = 'BRAND_REQUEST';
export const BRAND_SUCCESS = 'BRAND_SUCCESS';
export const BRAND_FAIL = 'BRAND_FAIL';
export const BRAND_RESET = 'BRAND_RESET';

export const BRAND_ADDRESS_REQUEST = 'BRAND_ADDRESS_REQUEST';
export const BRAND_ADDRESS_SUCCESS = 'BRAND_ADDRESS_SUCCESS';
export const BRAND_ADDRESS_FAIL = 'BRAND_ADDRESS_FAIL';
export const BRAND_ADDRESS_RESET = 'BRAND_ADDRESS_RESET';