export const BRAND_REQUEST = 'BRAND_REQUEST';
export const BRAND_SUCCESS = 'BRAND_SUCCESS';
export const BRAND_FAIL = 'BRAND_FAIL';
export const BRAND_RESET = 'BRAND_RESET';

export const BRAND_UPDATE_REQUEST = 'BRAND_UPDATE_REQUEST';
export const BRAND_UPDATE_SUCCESS = 'BRAND_UPDATE_SUCCESS';
export const BRAND_UPDATE_FAIL = 'BRAND_UPDATE_FAIL';
export const BRAND_UPDATE_RESET = 'BRAND_UPDATE_RESET';

export const BRAND_DELETE_REQUEST = 'BRAND_DELETE_REQUEST';
export const BRAND_DELETE_SUCCESS = 'BRAND_DELETE_SUCCESS';
export const BRAND_DELETE_FAIL = 'BRAND_DELETE_FAIL';
export const BRAND_DELETE_RESET = 'BRAND_DELETE_RESET';

export const BRAND_ADDRESS_REQUEST = 'BRAND_ADDRESS_REQUEST';
export const BRAND_ADDRESS_SUCCESS = 'BRAND_ADDRESS_SUCCESS';
export const BRAND_ADDRESS_FAIL = 'BRAND_ADDRESS_FAIL';
export const BRAND_ADDRESS_RESET = 'BRAND_ADDRESS_RESET';
