export const CAT_PRODUCT_REQUEST = 'CAT_PRODUCT_REQUEST';
export const CAT_PRODUCT_SUCCESS = 'CAT_PRODUCT_SUCCESS';
export const CAT_PRODUCT_FAIL = 'CAT_PRODUCT_FAIL';
export const CAT_PRODUCT_RESET = 'CAT_PRODUCT_RESET';