export const CAT_PRODUCT_REQUEST = 'CAT_PRODUCT_REQUEST';
export const CAT_PRODUCT_SUCCESS = 'CAT_PRODUCT_SUCCESS';
export const CAT_PRODUCT_FAIL = 'CAT_PRODUCT_FAIL';
export const CAT_PRODUCT_RESET = 'CAT_PRODUCT_RESET';

export const CAT_PRODUCT_SAVE_REQUEST = 'CAT_PRODUCT_SAVE_REQUEST';
export const CAT_PRODUCT_SAVE_SUCCESS = 'CAT_PRODUCT_SAVE_SUCCESS';
export const CAT_PRODUCT_SAVE_FAIL = 'CAT_PRODUCT_SAVE_FAIL';
export const CAT_PRODUCT_SAVE_RESET = 'CAT_PRODUCT_SAVE_RESET';

export const CAT_PRODUCT_UPDATE_REQUEST = 'CAT_PRODUCT_UPDATE_REQUEST';
export const CAT_PRODUCT_UPDATE_SUCCESS = 'CAT_PRODUCT_UPDATE_SUCCESS';
export const CAT_PRODUCT_UPDATE_FAIL = 'CAT_PRODUCT_UPDATE_FAIL';
export const CAT_PRODUCT_UPDATE_RESET = 'CAT_PRODUCT_UPDATE_RESET';

export const CAT_PRODUCT_DELETE_REQUEST = 'CAT_PRODUCT_DELETE_REQUEST';
export const CAT_PRODUCT_DELETE_SUCCESS = 'CAT_PRODUCT_DELETE_SUCCESS';
export const CAT_PRODUCT_DELETE_FAIL = 'CAT_PRODUCT_DELETE_FAIL';
export const CAT_PRODUCT_DELETE_RESET = 'CAT_PRODUCT_DELETE_RESET';

export const CAT_PRODUCT_DETAILS_REQUEST = 'CAT_PRODUCT_DETAILS_REQUEST';
export const CAT_PRODUCT_DETAILS_SUCCESS = 'CAT_PRODUCT_DETAILS_SUCCESS';
export const CAT_PRODUCT_DETAILS_FAIL = 'CAT_PRODUCT_DETAILS_FAIL';
export const CAT_PRODUCT_DETAILS_RESET = 'CAT_PRODUCT_DETAILS_RESET';
