export const CAT_PRODUCT_REQUEST = 'CAT_PRODUCT_REQUEST';
export const CAT_PRODUCT_SUCCESS = 'CAT_PRODUCT_SUCCESS';
export const CAT_PRODUCT_FAIL = 'CAT_PRODUCT_FAIL';
export const CAT_PRODUCT_RESET = 'CAT_PRODUCT_RESET';

export const CAT_QTY_CREATE_REQUEST = "CAT_QTY_CREATE_REQUEST";
export const CAT_QTY_CREATE_SUCCESS = "CAT_QTY_CREATE_SUCCESS";
export const CAT_QTY_CREATE_FAIL = "CAT_QTY_CREATE_FAIL";
export const CAT_QTY_CREATE_RESET = "CAT_QTY_CREATE_RESET";
