export const CATEGORY_MASTER_CREATE_REQUEST = "CATEGORY_MASTER_CREATE_REQUEST";
export const CATEGORY_MASTER_CREATE_SUCCESS = "CATEGORY_MASTER_CREATE_SUCCESS";
export const CATEGORY_MASTER_CREATE_FAIL = "CATEGORY_MASTER_CREATE_FAIL";
export const CATEGORY_MASTER_CREATE_RESET = "CATEGORY_MASTER_CREATE_RESET";

export const CATEGORY_MASTER_ALLLIST_REQUEST = "CATEGORY_MASTER_ALLLIST_REQUEST";
export const CATEGORY_MASTER_ALLLIST_SUCCESS = "CATEGORY_MASTER_ALLLIST_SUCCESS";
export const CATEGORY_MASTER_ALLLIST_FAIL = "CATEGORY_MASTER_ALLLIST_FAIL";

export const CATEGORY_MASTER_DEL_REQUEST = 'CATEGORY_MASTER_DEL_REQUEST';
export const CATEGORY_MASTER_DEL_SUCCESS = 'CATEGORY_MASTER_DEL_SUCCESS';
export const CATEGORY_MASTER_DEL_FAIL = 'CATEGORY_MASTER_DEL_FAIL';
export const CATEGORY_MASTER_DEL_RESET = 'CATEGORY_MASTER_DEL_RESET';

export const CATEGORY_MASTER_UPDATES_REQUEST = 'CATEGORY_MASTER_UPDATES_REQUEST';
export const CATEGORY_MASTER_UPDATES_SUCCESS = 'CATEGORY_MASTER_UPDATES_SUCCESS';
export const CATEGORY_MASTER_UPDATES_FAIL = 'CATEGORY_MASTER_UPDATES_FAIL';
export const CATEGORY_MASTER_UPDATES_RESET = 'CATEGORY_MASTER_UPDATES_RESET';